### ISSUE TITLE
Arakoon config path not correct for a remote backend

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/openvstorage-health-check#339] opened 2017-06-01 08:17 UTC
## Problem description

setup:
global ovs env
local ovs env

We created on the global env a vpool with a remote backend.
The problem we occurred is that the healthcheck try to search the arakoon key for the remote backend.
This is not present on the global env.

## Possible root of the problem

using the Arakoon key of a remote backend will not work. You should get this from the remote backend or capture this via the proxy?

### Logs
```
[INFO] Checking the ALBA proxies.
[INFO] Checking ALBA proxy albaproxy_mytestvpool_3.
[FAILED] Listing the presets has failed. Please check the arakoon config path. We used arakoon://config/ovs/arakoon/ny1-hddbackend01-abm/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini
[INFO] Checking ALBA proxy albaproxy_mytestvpool_1.
[FAILED] Listing the presets has failed. Please check the arakoon config path. We used arakoon://config/ovs/arakoon/ny1-hddbackend01-abm/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini
[INFO] Checking ALBA proxy albaproxy_mytestvpool_0.
[FAILED] Listing the presets has failed. Please check the arakoon config path. We used arakoon://config/ovs/arakoon/ny1-hddbackend01-abm/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini
[INFO] Checking ALBA proxy albaproxy_mytestvpool_2.
[FAILED] Listing the presets has failed. Please check the arakoon config path. We used arakoon://config/ovs/arakoon/ny1-hddbackend01-abm/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini
[INFO] Fetching available arakoon clusters.
```

### Setup
- Geoscale

### Packages
// List packages in the code tags using dpkg -l | grep openvstorage
```
ii  openvstorage                         2.9.2-1                                    amd64        openvStorage
ii  openvstorage-backend                 1.8.1-1                                    amd64        openvStorage Backend plugin
ii  openvstorage-backend-core            1.8.1-1                                    amd64        openvStorage Backend plugin core
ii  openvstorage-backend-webapps         1.8.1-1                                    amd64        openvStorage Backend plugin Web Applications
ii  openvstorage-core                    2.9.2-1                                    amd64        openvStorage core
ii  openvstorage-health-check            3.3.1-1                                    amd64        Open vStorage HealthCheck
ii  openvstorage-sdm                     1.7.1-1                                    amd64        Open vStorage Backend ASD Manager
ii  openvstorage-webapps                 2.9.2-1                                    amd64        openvStorage Web Applications
```

**Comment by JeffreyDevloo** [comment] 2017-06-12 09:25
Might have to change our strategy here.

The issue is that the healthcheck was designed to run on the local node itself. However in this setup, the local node has a vpool attached to a remote backend which we cannot compute.
We can alter our strategy and work from the storagedriver level to fetch the presets.

**Comment by JeffreyDevloo** [comment] 2017-06-12 12:06
Will be fixed by:  https://github.com/openvstorage/openvstorage-health-check/pull/342

**Closed** 2017-06-14 14:41 UTC
Labels: priority_critical
