### ISSUE TITLE
halted volume test not working

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/openvstorage-health-check#477] opened 2018-06-04 11:22 UTC
# Problem
The halted volumes test on the HC reports that everything is okay while multiple volumes are down.

HC version: 3.4.10-1

```
root@NY2SRV0007:~# time ovs healthcheck volumedriver halted-volumes-test
[INFO] Starting OpenvStorage Healthcheck version 3.4.10-1
3.4.5-1
[INFO] ======================
[SKIPPED] Halted volumes test vPool data-g-05 - Skipping vPool data-g-05 because it is not living here.
[SKIPPED] Halted volumes test vPool data-ny1-02 - Skipping vPool data-ny1-02 because it is not living here.
[SKIPPED] Halted volumes test vPool fsmetadata-ny1-01 - Skipping vPool fsmetadata-ny1-01 because it is not living here.
[SKIPPED] Halted volumes test vPool os-ny1-01 - Skipping vPool os-ny1-01 because it is not living here.
[SKIPPED] Halted volumes test vPool fsmetadata-ny2-01 - Skipping vPool fsmetadata-ny2-01 because it is not living here.
[INFO] Halted volumes test vPool ss-ny2-01 - Retrieving all information
[INFO] Halted volumes test vPool ss-ny2-01 - Scanning for halted volumes
[SUCCESS] Halted volumes test vPool ss-ny2-01 - No volumes found in halted/fenced state
[SKIPPED] Halted volumes test vPool ss-ny1-04 - Skipping vPool ss-ny1-04 because it is not living here.
[INFO] Halted volumes test vPool data-ny2-01 - Retrieving all information
[INFO] Halted volumes test vPool data-ny2-01 - Scanning for halted volumes
[SUCCESS] Halted volumes test vPool data-ny2-01 - No volumes found in halted/fenced state
[SKIPPED] Halted volumes test vPool os-ny2-01 - Skipping vPool os-ny2-01 because it is not living here.
[INFO] Halted volumes test vPool data-g-03 - Retrieving all information
[INFO] Halted volumes test vPool data-g-03 - Scanning for halted volumes
[SUCCESS] Halted volumes test vPool data-g-03 - No volumes found in halted/fenced state
[INFO] Halted volumes test vPool ss-ny2-02 - Retrieving all information
[INFO] Halted volumes test vPool ss-ny2-02 - Scanning for halted volumes
[SUCCESS] Halted volumes test vPool ss-ny2-02 - No volumes found in halted/fenced state
[SKIPPED] Halted volumes test vPool ss-ny1-03 - Skipping vPool ss-ny1-03 because it is not living here.
[SKIPPED] Halted volumes test vPool data-ny1-04 - Skipping vPool data-ny1-04 because it is not living here.
[INFO] Halted volumes test vPool data-ny2-02 - Retrieving all information
[INFO] Halted volumes test vPool data-ny2-02 - Scanning for halted volumes
[SUCCESS] Halted volumes test vPool data-ny2-02 - No volumes found in halted/fenced state
[SKIPPED] Halted volumes test vPool os-ny2-02 - Skipping vPool os-ny2-02 because it is not living here.
[SKIPPED] Halted volumes test vPool data-ny1-03 - Skipping vPool data-ny1-03 because it is not living here.
[SKIPPED] Halted volumes test vPool data-ny1-06 - Skipping vPool data-ny1-06 because it is not living here.
[SKIPPED] Halted volumes test vPool ss-ny1-02 - Skipping vPool ss-ny1-02 because it is not living here.
[SKIPPED] Halted volumes test vPool data-ny1-05 - Skipping vPool data-ny1-05 because it is not living here.
[SKIPPED] Halted volumes test vPool ss-ny1-01 - Skipping vPool ss-ny1-01 because it is not living here.
[SKIPPED] Halted volumes test vPool data-ny1-01 - Skipping vPool data-ny1-01 because it is not living here.
[INFO] Recap of Health Check!
[INFO] ======================
[INFO] SUCCESS=5 FAILED=0 SKIPPED=16 WARNING=0 EXCEPTION=0

real	0m1.463s
user	0m0.948s
sys	0m0.204s
```

volumedriver reports halted volume:

```
root@NY2SRV0007:~# journalctl --since '30 minutes ago' -ocat | grep 'failed to open volume'
2018-06-04 06:51:05 844741 -0400 - NY2SRV0007 - 6564/0x00007f966a330700 - volumedriverfs/NetworkXioIOHandler - 00000000000224e9 - error - handle_open: failed to open volume 'pcd_426547a3-ac89-423a-9ad2-b9d4be4851a1' Volume location not found c4781340-e155-4a2f-ab93-60faf4b7c7fb
2018-06-04 07:06:00 545769 -0400 - NY2SRV0007 - 6564/0x00007f966a330700 - volumedriverfs/NetworkXioIOHandler - 0000000000024c31 - error - handle_open: failed to open volume 'pcd_426547a3-ac89-423a-9ad2-b9d4be4851a1' Volume location not found c4781340-e155-4a2f-ab93-60faf4b7c7fb
2018-06-04 07:06:10 848548 -0400 - NY2SRV0007 - 6564/0x00007f966a330700 - volumedriverfs/NetworkXioIOHandler - 0000000000024c78 - error - handle_open: failed to open volume 'pcd_426547a3-ac89-423a-9ad2-b9d4be4851a1' Volume location not found c4781340-e155-4a2f-ab93-60faf4b7c7fb
```

volume info:
```
In [4]: vd = VDiskList.get_vdisk_by_volume_id('c4781340-e155-4a2f-ab93-60faf4b7c7fb')

In [5]: vd._info()
Out[5]: 
{'cluster_cache_handle': ClusterCacheHandle(0),
 'cluster_cache_limit': None,
 'cluster_multiplier': 0,
 'failover_ip': '',
 'failover_mode': '',
 'failover_port': 0,
 'footprint': 0,
 'halted': False,
 'lba_count': 0,
 'lba_size': 0,
 'live_status': 'NON_RUNNING',
 'metadata_backend_config': {},
 'namespace': '',
 'object_type': 'FILE',
 'owner_tag': OwnerTag(0),
 'parent_namespace': '',
 'parent_snapshot_id': '',
 'parent_volume_id': '',
 'sco_multiplier': 0,
 'stored': 0,
 'volume_id': '',
 'volume_size': 0,
 'vrouter_id': ''}
```

**Comment by JeffreyDevloo** [comment] 2018-06-04 12:09
Duplicate of https://github.com/openvstorage/openvstorage-health-check/issues/433
Its not a bug, intended. The previous iteration was a bit funky

**Closed by JeffreyDevloo** 2018-06-04 12:09 UTC
Labels: type_bug
