### ISSUE TITLE
Missing ovs-sdm package is throwing error instead of skipped/warning

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/openvstorage-health-check#280] opened 2017-02-13 15:53 UTC
## Problem:
Missing package is reported as ERROR while it should be SKIPPED or WARNING.

## Logs
```
1 failure(s) found during the healthcheck run: {'ovs-packages-test': {'state': 'FAILED', 'messages': OrderedDict([('error', [{'message': 'Package openvstorage-sdm is not installed.',
```

**Comment by JeffreyDevloo** [comment] 2017-02-13 15:54
Duplicate of https://github.com/openvstorage/openvstorage-health-check/issues/274

**Comment by kinvaris** [comment] 2017-02-13 15:59
@JeffreyDevloo that ticket is closes but not fixed.

Here is more output BTW

```
root@ctrl-221-1:~# ovs healthcheck ovs packages-test
[INFO] Storagerouter Type: MASTER
[INFO] Environment Os: Ubuntu 16.04 xenial
[INFO] Environment Release: Fargo
[INFO] Hostname: ctrl-221-1
[INFO] Cluster Id: rH9V3k5gXPRTFEbB
[INFO] Storagerouter Id: MG12W5NRvxJaCNqW
[INFO] Starting OpenvStorage Healthcheck version 3.2.0-rev.458.32b1ede-1
[INFO] ======================
[INFO] Checking OVS packages: 
[SUCCESS] Package volumedriver-no-dedup-server is installed with version 6.10.1-0
[SUCCESS] Package volumedriver-no-dedup-base is installed with version 6.10.1-0
[FAILED] Package openvstorage-sdm is not installed.
[SUCCESS] Package openvstorage-backend is installed with version 1.7.11.1-1
[SUCCESS] Package openvstorage is installed with version 2.7.11.1-1
[SUCCESS] Package arakoon is installed with version 1.9.15
[SUCCESS] Package alba is installed with version 1.3.6
[SUCCESS] Package openvstorage-health-check is installed with version 3.2.0-rev.458.32b1ede-1
[SUCCESS] Package blktap-openvstorage-utils is installed with version 2.0.90-2ubuntu5
[SKIPPED] Package libvirt-bin is not installed.
[SUCCESS] Package qemu is installed with version 99:2.5+dfsg-0ovs2.0-5ubuntu10.2
[SUCCESS] Package libovsvolumedriver is installed with version 6.10.1-0
[SUCCESS] Package avahi-utils is installed with version 0.6.32~rc+dfsg-1ubuntu2
[SUCCESS] Package avahi-daemon is installed with version 0.6.32~rc+dfsg-1ubuntu2
[SUCCESS] Package omniorb-nameserver is installed with version 4.1.6-2ubuntu1
[SKIPPED] Package python-libvirt is not installed.
[SKIPPED] Package libvirt0 is not installed.
[SUCCESS] Package volumedriver-no-dedup-server is installed with version 6.10.1-0
[SUCCESS] Package ntp is installed with version 1:4.2.8p4+dfsg-3ubuntu5.3
[SUCCESS] Package openvpn is installed with version 2.3.10-1ubuntu2
[SKIPPED] Package virtinst is not installed.
[SKIPPED] Package qemu-kvm is not installed.
[SUCCESS] Package rabbitmq-server is installed with version 3.5.7-1
[SUCCESS] Package memcached is installed with version 1.4.25-2ubuntu1.2
[SUCCESS] Package nginx is installed with version 1.10.0-0ubuntu0.16.04.4
[INFO] Recap of Health Check module ovs test packages-test!
[INFO] ======================
[INFO] SUCCESS=19 FAILED=1 SKIPPED=5 WARNING=0 EXCEPTION=0
```

**Comment by wimpers** [comment] 2017-02-23 13:56
@JeffreyDevloo  we assume this is a small one. revert if not the case.

**Comment by JeffreyDevloo** [comment] 2017-02-27 14:34
Was actually already tackled by the PR that I include but it wasn't packaged at the time.

```
[INFO] Storagerouter Type: MASTER
[INFO] Environment Os: Ubuntu 16.04 xenial
[INFO] Environment Release: Fargo
[INFO] Hostname: jef-node1
[INFO] Cluster Id: pJwImxsRUPIfzOKS
[INFO] Storagerouter Id: Xynfj8u2Lw61VcIn
/usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py:141: FutureWarning: CTR mode needs counter parameter, not IV
  self._cipher = factory.new(key, *args, **kwargs)
[INFO] Starting OpenvStorage Healthcheck version 3.2.0-rev.471.aad652c-1
[INFO] ======================
[INFO] Checking OVS packages: 
[SUCCESS] Package volumedriver-no-dedup-server is installed with version 6.10.1-dev.201702210225.99f9492
[SUCCESS] Package volumedriver-no-dedup-base is installed with version 6.10.1-dev.201702210225.99f9492
[WARNING] Package openvstorage-sdm is not installed.
[SUCCESS] Package openvstorage-backend is installed with version 1.7.12.1-1
[SUCCESS] Package openvstorage is installed with version 2.7.12.1-1
[SUCCESS] Package arakoon is installed with version 1.9.15
[SUCCESS] Package alba is installed with version 1.3.6
[SUCCESS] Package openvstorage-health-check is installed with version 3.2.0-rev.471.aad652c-1
[SKIPPED] Package blktap-openvstorage-utils is not installed.
[SUCCESS] Package libvirt-bin is installed with version 1.3.1-0ovs2.0-1ubuntu10.5
[SKIPPED] Package qemu is not installed.
[SUCCESS] Package libovsvolumedriver is installed with version 6.10.1-dev.201702210225.99f9492
[SUCCESS] Package avahi-utils is installed with version 0.6.32~rc+dfsg-1ubuntu2
[SUCCESS] Package avahi-daemon is installed with version 0.6.32~rc+dfsg-1ubuntu2
[SUCCESS] Package omniorb-nameserver is installed with version 4.1.6-2ubuntu1
[SUCCESS] Package python-libvirt is installed with version 1.3.1-1ubuntu12.7
[SUCCESS] Package libvirt0 is installed with version 1.3.1-0ovs2.0-1ubuntu10.5
[SUCCESS] Package volumedriver-no-dedup-server is installed with version 6.10.1-dev.201702210225.99f9492
[SUCCESS] Package ntp is installed with version 1:4.2.8p4+dfsg-3ubuntu5.3
[SUCCESS] Package openvpn is installed with version 2.3.10-1ubuntu2
[SUCCESS] Package virtinst is installed with version 1:1.3.2-3ubuntu1.16.04.3
[SUCCESS] Package qemu-kvm is installed with version 99:2.5+dfsg-0ovs2.0-5ubuntu10.2
[SUCCESS] Package rabbitmq-server is installed with version 3.5.7-1
[SUCCESS] Package memcached is installed with version 1.4.25-2ubuntu1.2
[SUCCESS] Package nginx is installed with version 1.10.0-0ubuntu0.16.04.4
[INFO] Recap of Health Check module ovs test packages-test!
[INFO] ======================
[INFO] SUCCESS=22 FAILED=0 SKIPPED=2 WARNING=1 EXCEPTION=0
root@jef-node1:~# 

```

**Closed by JeffreyDevloo** 2017-02-27 14:34 UTC
Labels: priority_minor, type_bug
