### ISSUE TITLE
Detect arakoon collapse problems

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/openvstorage-health-check#51] opened 2016-06-22 13:38 UTC
**Detecting arakoon collapse problems:**
check 10 oldest tlx file with newest and last collapse. 

It is important to check the last 10 so you don't get false positives, because after each collapse 2  newest tlx files are kept from the last collapse.

**Possible way to detect it:**
```
root@ctrl-roub-01:~# ls -alsh /mnt/ssd1/arakoon/voldrv/db/PuUmYee3ecixvGXU.db
344K -rwxr-xr-x 1 ovs ovs 341K Jun 22 15:40 /mnt/ssd1/arakoon/voldrv/db/PuUmYee3ecixvGXU.db

root@ctrl-roub-01:~# ls -alsh /mnt/ssd1/arakoon/voldrv/tlogs/head.db 
344K -rw-r--r-- 1 ovs ovs 341K Jun 22 15:01 /mnt/ssd1/arakoon/voldrv/tlogs/head.db <-- last collapse?

root@ctrl-roub-01:~# date
Wed Jun 22 15:41:10 CEST 2016
```

**Comment by wimpers** [comment] 2016-08-10 08:21
Duplicate of https://github.com/openvstorage/openvstorage-health-check/issues/72 ?

**Comment by JeffreyDevloo** [comment] 2016-10-26 15:40
Indeed duplicate of #72

**Closed by JeffreyDevloo** 2016-10-26 15:40 UTC
Labels: type_feature
