### ISSUE TITLE
RuntimeError: database is locked

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/openvstorage-health-check#349] opened 2017-06-29 20:41 UTC
```
root@NY2SRV0014:~# ovs healthcheck alba backend-test
[INFO] Storagerouter Id: bwG03NOvf7vw0le7
[INFO] Environment Os: Ubuntu 16.04 xenial
[INFO] Hostname: NY2SRV0014
[INFO] Cluster Id: ZGeSQq7dS2IoG8Bp
[INFO] Storagerouter Type: MASTER
[INFO] Starting OpenvStorage Healthcheck version 3.3.5-1
[INFO] ======================
[INFO] Checking available ALBA backends.
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/OpenvStorage/ovs/dal/hybrids/albabackend.py", line 97, in _load_live_info
    _data = _node.storage_stack
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 345, in <lambda>
    fget = lambda s: s._get_dynamic_property(dynamic)
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 414, in _get_dynamic_property
    return self._backend_property(data_loader, dynamic)
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 1011, in _backend_property
    dynamic_data = function()
  File "/opt/OpenvStorage/ovs/dal/hybrids/albanode.py", line 105, in _storage_stack
    asd_data = self.client.get_asds()
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 179, in get_asds
    return self._call(requests.get, 'asds', clean=True)
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 107, in _call
    raise RuntimeError(error_message)
RuntimeError: database is locked

[SUCCESS] We found 4 backend(s)!
[INFO] Checking the ALBA ASDs.                                                                                                                                                                                                    
[INFO] Checking separate ASDs for backend ny2-ssdbackend01:  
```

**Comment by JeffreyDevloo** [comment] 2017-07-07 08:12
Related
https://github.com/openvstorage/alba-asdmanager/issues/255

**Comment by JeffreyDevloo** [comment] 2017-07-10 15:04
The related ticket is actually the cause, closing

**Closed by JeffreyDevloo** 2017-07-10 15:04 UTC
